export const LOAD_EXROOMS_DATA_PENDING = 'LOAD_EXROOMS_DATA_PENDING';
export const LOAD_EXROOMS_DATA_SUCCESS = 'LOAD_EXROOMS_DATA_SUCCESS';
export const LOAD_EXROOMS_DATA_ERROR = 'LOAD_EXROOMS_DATA_ERROR';
